
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dumbstore-web
  labels:
    app: dumbstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dumbstore
  template:
    metadata:
      labels:
        app: dumbstore
    spec:
      containers:
      - name: dumbstore-web
        image: "dumbstore:2.0.1"
        env:
          - name: REDIS_HOST
            value: "dumbstore-redis-master:6379"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dumbstore-redis
                key: redis-password
          - name: LOG_LEVEL
            valueFrom:
              secretKeyRef:
                name: log-config
                key: log-level
